server:
  appName: keeper-gateway
  port: 8080
  ip: host.docker.internal
  eureka:
    enabled: true
    hostname: host.docker.internal
    prefer-ip: false
  logging:
    level: info
    filePath: ../logs/gateway/gateway.log

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 2400s
        pool:
          type: elastic
          max-idle-time: 300s
      routes:
        - id: keeper-eureka
          uri: http://keeper-eureka:8761
          predicates:
            Path=/eureka/web
          filters:
            SetPath=/

        - id: keeper-eureka-static
          uri: http://keeper-eureka:8761
          predicates:
            - Path=/eureka/**

        - id: keeper-security
          uri: lb://keeper-security
          predicates:
            - Path=/api/v*/auth/**

        - id: keeper-panda
          uri: lb://keeper-panda
          predicates:
            - Path=/api/v*/panda/**

        - id: keeper-events
          uri: lb://keeper-events
          predicates:
            - Path=/api/v*/events/**

        - id: keeper-telbot
          uri: lb://keeper-telbot
          predicates:
            - Path=/api/v*/telbot**

        - id: keeper-storage
          uri: http://keeper-storage:8020
          predicates:
            - Path=/api/v*/storage/**
