server:
  appName: keeper-gateway-service
  port: 8080
  ip: 192.168.100.8
  logging:
    level: info
    filePath: ../logs/gateway/gateway.log

spring:
  cloud:
    gateway:
      routes:
        - id: eureka-server
          uri: http://${server.ip}:8761
          predicates:
            Path=/eureka/web
          filters:
            SetPath=/

        - id: eureka-server-static
          uri: http://${server.ip}:8761
          predicates:
            - Path=/eureka/**

        - id: keeper-security-service
          uri: lb://keeper-security-service
          predicates:
            - Path=/api/auth/**